-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS rerouteher.app_user
(
    auth_subject text COLLATE pg_catalog."default" NOT NULL,
    identity_provider text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone,
    CONSTRAINT app_user_pkey PRIMARY KEY (auth_subject)
);

COMMENT ON TABLE rerouteher.app_user
    IS 'Local identity reference only. Reusable passwords and email ownership remain with the identity provider.';

CREATE TABLE IF NOT EXISTS rerouteher.bursa_sectors
(
    sector_id text COLLATE pg_catalog."default" NOT NULL,
    sector_name text COLLATE pg_catalog."default" NOT NULL,
    classification text COLLATE pg_catalog."default" NOT NULL,
    source_table text COLLATE pg_catalog."default" NOT NULL,
    review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bursa_sectors_pkey PRIMARY KEY (sector_id),
    CONSTRAINT bursa_sectors_sector_name_key UNIQUE (sector_name)
);

CREATE TABLE IF NOT EXISTS rerouteher.caregiving_map
(
    activity_id text COLLATE pg_catalog."default" NOT NULL,
    break_activity text COLLATE pg_catalog."default" NOT NULL,
    mapping_rank integer NOT NULL,
    onet_skill_id text COLLATE pg_catalog."default" NOT NULL,
    onet_skill_name text COLLATE pg_catalog."default" NOT NULL,
    reframed_label text COLLATE pg_catalog."default" NOT NULL,
    mapping_method text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT caregiving_map_pkey PRIMARY KEY (activity_id, mapping_rank)
);

CREATE TABLE IF NOT EXISTS rerouteher.d9_target_role_mapping
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    role_title text COLLATE pg_catalog."default" NOT NULL,
    masco_2020_code text COLLATE pg_catalog."default" NOT NULL,
    jobhop_isco08_target_group text COLLATE pg_catalog."default" NOT NULL,
    anchor_esco_code text COLLATE pg_catalog."default" NOT NULL,
    anchor_esco_title text COLLATE pg_catalog."default" NOT NULL,
    official_onet_code text COLLATE pg_catalog."default" NOT NULL,
    jobhop_records_in_group integer NOT NULL,
    jobhop_resumes_in_group integer NOT NULL,
    latest_resume_targets_in_group integer NOT NULL,
    mapping_method text COLLATE pg_catalog."default" NOT NULL,
    review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT d9_target_role_mapping_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.d9_training_examples
(
    resume_id bigint NOT NULL,
    split text COLLATE pg_catalog."default" NOT NULL,
    role_id text COLLATE pg_catalog."default" NOT NULL,
    target_esco_code text COLLATE pg_catalog."default" NOT NULL,
    target_esco_title text COLLATE pg_catalog."default" NOT NULL,
    previous_esco_codes text COLLATE pg_catalog."default" NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    feature_definition text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT d9_training_examples_pkey PRIMARY KEY (resume_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.data_dictionary
(
    table_name text COLLATE pg_catalog."default" NOT NULL,
    primary_key_description text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    missing_rule text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT data_dictionary_pkey PRIMARY KEY (table_name)
);

CREATE TABLE IF NOT EXISTS rerouteher.data_lineage
(
    deliverable text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    transform text COLLATE pg_catalog."default" NOT NULL,
    output text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT data_lineage_pkey PRIMARY KEY (deliverable)
);

CREATE TABLE IF NOT EXISTS rerouteher.dataset_metadata
(
    metadata_key text COLLATE pg_catalog."default" NOT NULL,
    metadata_value jsonb NOT NULL,
    CONSTRAINT dataset_metadata_pkey PRIMARY KEY (metadata_key)
);

CREATE TABLE IF NOT EXISTS rerouteher.digcomp_competences
(
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    digcomp_id text COLLATE pg_catalog."default" NOT NULL,
    canonical_name text COLLATE pg_catalog."default" NOT NULL,
    competence_area text COLLATE pg_catalog."default" NOT NULL,
    definition text COLLATE pg_catalog."default",
    source_framework text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT digcomp_competences_pkey PRIMARY KEY (skill_id),
    CONSTRAINT digcomp_competences_digcomp_id_key UNIQUE (digcomp_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.digital_skill_rating_lineage
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    skill_name text COLLATE pg_catalog."default" NOT NULL,
    skill_type text COLLATE pg_catalog."default" NOT NULL,
    importance double precision,
    source text COLLATE pg_catalog."default" NOT NULL,
    source_occupation_code text COLLATE pg_catalog."default",
    source_element_id text COLLATE pg_catalog."default",
    importance_method text COLLATE pg_catalog."default",
    curation_note text COLLATE pg_catalog."default",
    raw_source_value text COLLATE pg_catalog."default",
    normalisation_or_rating_rule text COLLATE pg_catalog."default",
    one_line_justification text COLLATE pg_catalog."default",
    source_url text COLLATE pg_catalog."default",
    review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT digital_skill_rating_lineage_pkey PRIMARY KEY (role_id, skill_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.employer_evidence
(
    evidence_id text COLLATE pg_catalog."default" NOT NULL,
    employer_id text COLLATE pg_catalog."default" NOT NULL,
    employer_name text COLLATE pg_catalog."default" NOT NULL,
    pillar text COLLATE pg_catalog."default" NOT NULL,
    fact_field text COLLATE pg_catalog."default" NOT NULL,
    extracted_value text COLLATE pg_catalog."default" NOT NULL,
    unit text COLLATE pg_catalog."default",
    source_year integer,
    source_url text COLLATE pg_catalog."default" NOT NULL,
    page_or_section text COLLATE pg_catalog."default" NOT NULL,
    evidence_paraphrase text COLLATE pg_catalog."default",
    verification_status text COLLATE pg_catalog."default" NOT NULL,
    reviewer text COLLATE pg_catalog."default",
    review_date date,
    CONSTRAINT employer_evidence_pkey PRIMARY KEY (evidence_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.employer_report_evidence
(
    employer_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    report_year integer,
    report_url text COLLATE pg_catalog."default",
    page_or_section text COLLATE pg_catalog."default",
    women_workforce_pct double precision,
    women_management_pct double precision,
    women_board_pct double precision,
    maternity_days integer,
    paternity_days integer,
    flexible_remote_disclosed boolean,
    childcare_nursing_phased_return boolean,
    evidence_note text COLLATE pg_catalog."default",
    recognition_note text COLLATE pg_catalog."default",
    extraction_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employer_report_evidence_pkey PRIMARY KEY (employer_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.employer_report_search
(
    employer_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    search_status text COLLATE pg_catalog."default" NOT NULL,
    has_report boolean NOT NULL,
    report_year integer,
    report_url text COLLATE pg_catalog."default",
    recognition_search_status text COLLATE pg_catalog."default" NOT NULL,
    no_report_zero_rule_applied boolean NOT NULL,
    search_completion_note text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employer_report_search_pkey PRIMARY KEY (employer_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.employer_review_queue
(
    employer_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    priority text COLLATE pg_catalog."default" NOT NULL,
    review_status text COLLATE pg_catalog."default" NOT NULL,
    checks_required text COLLATE pg_catalog."default" NOT NULL,
    reviewer text COLLATE pg_catalog."default",
    review_date date,
    decision text COLLATE pg_catalog."default",
    review_notes text COLLATE pg_catalog."default",
    CONSTRAINT employer_review_queue_pkey PRIMARY KEY (employer_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.employer_scoring_rules
(
    pillar text COLLATE pg_catalog."default" NOT NULL,
    component text COLLATE pg_catalog."default" NOT NULL,
    points_or_weight text COLLATE pg_catalog."default" NOT NULL,
    rule text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employer_scoring_rules_pkey PRIMARY KEY (pillar, component)
);

CREATE TABLE IF NOT EXISTS rerouteher.employers
(
    employer_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    sector_id text COLLATE pg_catalog."default" NOT NULL,
    sector text COLLATE pg_catalog."default" NOT NULL,
    has_report boolean NOT NULL,
    report_year integer,
    report_url text COLLATE pg_catalog."default",
    recognition_score double precision NOT NULL,
    gender_equity_score double precision NOT NULL,
    policy_flex_score double precision NOT NULL,
    mother_friendly_score double precision NOT NULL,
    confidence text COLLATE pg_catalog."default" NOT NULL,
    score_status text COLLATE pg_catalog."default" NOT NULL,
    evidence_status text COLLATE pg_catalog."default" NOT NULL,
    scoring_rule text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employers_pkey PRIMARY KEY (employer_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.esco_onet_crosswalk
(
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    esco_title text COLLATE pg_catalog."default" NOT NULL,
    onet_soc_code text COLLATE pg_catalog."default" NOT NULL,
    onet_title text COLLATE pg_catalog."default" NOT NULL,
    crosswalk_source text COLLATE pg_catalog."default" NOT NULL,
    source_url text COLLATE pg_catalog."default" NOT NULL,
    retrieved_date date,
    CONSTRAINT esco_onet_crosswalk_pkey PRIMARY KEY (esco_code, onet_soc_code, esco_title, onet_title)
);

CREATE TABLE IF NOT EXISTS rerouteher.jobhop_esco_features
(
    jobhop_feature_id bigint NOT NULL,
    resume_id bigint NOT NULL,
    matched_code text COLLATE pg_catalog."default" NOT NULL,
    start_date text COLLATE pg_catalog."default" NOT NULL,
    end_date text COLLATE pg_catalog."default" NOT NULL,
    university_level text COLLATE pg_catalog."default" NOT NULL,
    split text COLLATE pg_catalog."default" NOT NULL,
    start_year integer NOT NULL,
    end_year integer NOT NULL,
    work_length_years_est double precision NOT NULL,
    work_length_months_est integer NOT NULL,
    work_length_band text COLLATE pg_catalog."default" NOT NULL,
    resume_job_count integer NOT NULL,
    resume_total_role_years_est double precision NOT NULL,
    resume_first_start_year integer NOT NULL,
    resume_last_end_year integer NOT NULL,
    resume_span_years_est double precision NOT NULL,
    esco_code text COLLATE pg_catalog."default",
    esco_title text COLLATE pg_catalog."default",
    esco_occupation_uri text COLLATE pg_catalog."default",
    top_skill_groups text COLLATE pg_catalog."default",
    top_skill_groups_weighted text COLLATE pg_catalog."default",
    top_skill_count integer,
    mapping_status text COLLATE pg_catalog."default" NOT NULL,
    masco_candidate_code text COLLATE pg_catalog."default",
    masco_unit_group_title_en text COLLATE pg_catalog."default",
    masco_mapping_status text COLLATE pg_catalog."default",
    skill_feature_text text COLLATE pg_catalog."default",
    CONSTRAINT jobhop_esco_features_pkey PRIMARY KEY (jobhop_feature_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.jobhop_esco_onet_coverage
(
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    source_records integer NOT NULL,
    source_resumes integer NOT NULL,
    official_crosswalk_row_count integer NOT NULL,
    unique_onet_code_count integer NOT NULL,
    onet_codes text COLLATE pg_catalog."default",
    onet_titles text COLLATE pg_catalog."default",
    coverage_status text COLLATE pg_catalog."default" NOT NULL,
    production_rule text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT jobhop_esco_onet_coverage_pkey PRIMARY KEY (esco_code)
);

CREATE TABLE IF NOT EXISTS rerouteher.learning_resource
(
    resource_id text COLLATE pg_catalog."default" NOT NULL,
    provider_id text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    delivery_mode text COLLATE pg_catalog."default",
    duration interval,
    language text COLLATE pg_catalog."default",
    level text COLLATE pg_catalog."default",
    licence_note text COLLATE pg_catalog."default",
    last_verified_at timestamp with time zone,
    CONSTRAINT learning_resource_pkey PRIMARY KEY (resource_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.learning_resource_skill
(
    resource_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    relevance numeric(5, 2),
    evidence_note text COLLATE pg_catalog."default",
    CONSTRAINT learning_resource_skill_pkey PRIMARY KEY (resource_id, skill_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.minilm_embeddings
(
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    embedding_index integer NOT NULL,
    model_name text COLLATE pg_catalog."default" NOT NULL,
    dimensions integer NOT NULL,
    l2_normalized boolean NOT NULL,
    embedding real[] NOT NULL,
    CONSTRAINT minilm_embeddings_pkey PRIMARY KEY (esco_code),
    CONSTRAINT minilm_embeddings_embedding_index_key UNIQUE (embedding_index)
);

CREATE TABLE IF NOT EXISTS rerouteher.occupation_profiles
(
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    esco_title text COLLATE pg_catalog."default" NOT NULL,
    normalized_title text COLLATE pg_catalog."default" NOT NULL,
    esco_occupation_uri text COLLATE pg_catalog."default",
    esco_title_matrix text COLLATE pg_catalog."default",
    top_skill_groups text COLLATE pg_catalog."default",
    top_skill_groups_weighted text COLLATE pg_catalog."default",
    top_skill_count integer,
    mapping_status text COLLATE pg_catalog."default" NOT NULL,
    masco_candidate_code text COLLATE pg_catalog."default",
    masco_unit_group_title_en text COLLATE pg_catalog."default",
    masco_mapping_status text COLLATE pg_catalog."default" NOT NULL,
    jobhop_record_count integer NOT NULL,
    work_length_median_years double precision,
    work_length_mean_years double precision,
    work_length_p25_years double precision,
    work_length_p75_years double precision,
    CONSTRAINT occupation_profiles_pkey PRIMARY KEY (esco_code),
    CONSTRAINT occupation_profiles_esco_occupation_uri_key UNIQUE (esco_occupation_uri)
);

CREATE TABLE IF NOT EXISTS rerouteher.occupation_skill_weights
(
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    esco_occupation_uri text COLLATE pg_catalog."default" NOT NULL,
    esco_title text COLLATE pg_catalog."default" NOT NULL,
    skill_group_uri text COLLATE pg_catalog."default" NOT NULL,
    skill_group_label text COLLATE pg_catalog."default" NOT NULL,
    matrix_weight real NOT NULL,
    skill_rank integer NOT NULL,
    source_version text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT occupation_skill_weights_pkey PRIMARY KEY (esco_code, skill_group_uri)
);

CREATE TABLE IF NOT EXISTS rerouteher.official_role_crosswalk
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    role_title text COLLATE pg_catalog."default" NOT NULL,
    masco_2020_code text COLLATE pg_catalog."default" NOT NULL,
    masco_2020_title text COLLATE pg_catalog."default" NOT NULL,
    isco08_unit_group text COLLATE pg_catalog."default" NOT NULL,
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    esco_title text COLLATE pg_catalog."default" NOT NULL,
    onet_soc_2019_code text COLLATE pg_catalog."default" NOT NULL,
    onet_soc_2019_title text COLLATE pg_catalog."default" NOT NULL,
    masco_to_esco_method text COLLATE pg_catalog."default" NOT NULL,
    esco_to_onet_method text COLLATE pg_catalog."default" NOT NULL,
    crosswalk_review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT official_role_crosswalk_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.onet_task_context
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    task_rank integer NOT NULL,
    onet_task_id text COLLATE pg_catalog."default" NOT NULL,
    task_type text COLLATE pg_catalog."default",
    task text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT onet_task_context_pkey PRIMARY KEY (role_id, task_rank)
);

CREATE TABLE IF NOT EXISTS rerouteher.provider
(
    provider_id text COLLATE pg_catalog."default" NOT NULL,
    provider_name text COLLATE pg_catalog."default" NOT NULL,
    homepage_url text COLLATE pg_catalog."default",
    terms_url text COLLATE pg_catalog."default",
    CONSTRAINT provider_pkey PRIMARY KEY (provider_id),
    CONSTRAINT provider_provider_name_key UNIQUE (provider_name)
);

CREATE TABLE IF NOT EXISTS rerouteher.role_rating_lineage
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    role_title text COLLATE pg_catalog."default" NOT NULL,
    masco_code text COLLATE pg_catalog."default" NOT NULL,
    masco_source_page_pdf integer,
    rated_task_count integer NOT NULL,
    remote_capable_tasks integer NOT NULL,
    remote_onsite_tasks integer NOT NULL,
    remote_unclear_tasks integer NOT NULL,
    remote_pre_rating text COLLATE pg_catalog."default" NOT NULL,
    ai_exposable_tasks integer NOT NULL,
    ai_exposure_share double precision,
    ai_pre_rating text COLLATE pg_catalog."default" NOT NULL,
    independent_raters_required integer NOT NULL,
    reconciliation_status text COLLATE pg_catalog."default" NOT NULL,
    release_use text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_rating_lineage_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.role_sector_map
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    role_title text COLLATE pg_catalog."default" NOT NULL,
    sector_id text COLLATE pg_catalog."default" NOT NULL,
    sector text COLLATE pg_catalog."default" NOT NULL,
    mapping_purpose text COLLATE pg_catalog."default" NOT NULL,
    mapping_method text COLLATE pg_catalog."default" NOT NULL,
    evidence_basis text COLLATE pg_catalog."default",
    rationale text COLLATE pg_catalog."default",
    review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_sector_map_pkey PRIMARY KEY (role_id, sector_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.role_sector_review_queue
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    sector_id text COLLATE pg_catalog."default" NOT NULL,
    sector text COLLATE pg_catalog."default" NOT NULL,
    reviewer text COLLATE pg_catalog."default",
    review_date date,
    decision text COLLATE pg_catalog."default",
    review_notes text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_sector_review_queue_pkey PRIMARY KEY (role_id, sector_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.role_skill_lineage
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    skill_name text COLLATE pg_catalog."default" NOT NULL,
    skill_type text COLLATE pg_catalog."default" NOT NULL,
    importance double precision,
    source text COLLATE pg_catalog."default" NOT NULL,
    source_occupation_code text COLLATE pg_catalog."default",
    source_element_id text COLLATE pg_catalog."default",
    importance_method text COLLATE pg_catalog."default",
    curation_note text COLLATE pg_catalog."default",
    raw_source_value text COLLATE pg_catalog."default",
    normalisation_or_rating_rule text COLLATE pg_catalog."default",
    one_line_justification text COLLATE pg_catalog."default",
    source_url text COLLATE pg_catalog."default",
    review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_skill_lineage_pkey PRIMARY KEY (role_id, skill_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.role_skills
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    skill_name text COLLATE pg_catalog."default" NOT NULL,
    skill_type text COLLATE pg_catalog."default" NOT NULL,
    importance double precision NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    source_occupation_code text COLLATE pg_catalog."default",
    source_element_id text COLLATE pg_catalog."default",
    importance_method text COLLATE pg_catalog."default" NOT NULL,
    curation_note text COLLATE pg_catalog."default",
    CONSTRAINT role_skills_pkey PRIMARY KEY (role_id, skill_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.role_tasks
(
    masco_task_id text COLLATE pg_catalog."default" NOT NULL,
    role_id text COLLATE pg_catalog."default" NOT NULL,
    task_rank integer NOT NULL,
    masco_code text COLLATE pg_catalog."default" NOT NULL,
    task text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    source_page_pdf integer,
    CONSTRAINT role_tasks_pkey PRIMARY KEY (masco_task_id),
    CONSTRAINT role_tasks_role_id_task_rank_key UNIQUE (role_id, task_rank)
);

CREATE TABLE IF NOT EXISTS rerouteher.roles
(
    role_id text COLLATE pg_catalog."default" NOT NULL,
    role_title text COLLATE pg_catalog."default" NOT NULL,
    masco_code text COLLATE pg_catalog."default" NOT NULL,
    masco_title text COLLATE pg_catalog."default" NOT NULL,
    isco08_code text COLLATE pg_catalog."default" NOT NULL,
    esco_code text COLLATE pg_catalog."default" NOT NULL,
    onet_code text COLLATE pg_catalog."default" NOT NULL,
    task_summary text COLLATE pg_catalog."default" NOT NULL,
    occupation_description text COLLATE pg_catalog."default",
    remote_possibility text COLLATE pg_catalog."default",
    remote_task_count integer,
    remote_capable_tasks integer,
    remote_onsite_tasks integer,
    remote_unclear_tasks integer,
    remote_external_proxy text COLLATE pg_catalog."default",
    remote_justification text COLLATE pg_catalog."default",
    ai_exposure text COLLATE pg_catalog."default",
    ai_exposure_share double precision,
    ai_exposure_external_score_0_100 double precision,
    ai_exposure_measure text COLLATE pg_catalog."default",
    flexible_role boolean NOT NULL,
    rating_status text COLLATE pg_catalog."default" NOT NULL,
    embedding_model text COLLATE pg_catalog."default" NOT NULL,
    role_embedding vector(384) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.saved_journey
(
    journey_id uuid NOT NULL DEFAULT gen_random_uuid(),
    auth_subject text COLLATE pg_catalog."default" NOT NULL,
    role_id text COLLATE pg_catalog."default",
    current_step text COLLATE pg_catalog."default" NOT NULL DEFAULT 'profile'::text,
    snapshot_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT saved_journey_pkey PRIMARY KEY (journey_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.shortlist_item
(
    journey_id uuid NOT NULL,
    employer_id text COLLATE pg_catalog."default" NOT NULL,
    rank integer,
    score numeric(6, 2),
    reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT shortlist_item_pkey PRIMARY KEY (journey_id, employer_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.skill_aliases
(
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    alias_source text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT skill_aliases_pkey PRIMARY KEY (skill_id, alias)
);

CREATE TABLE IF NOT EXISTS rerouteher.skill_taxonomy
(
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    canonical_name text COLLATE pg_catalog."default" NOT NULL,
    definition text COLLATE pg_catalog."default",
    skill_type text COLLATE pg_catalog."default" NOT NULL,
    competence_area text COLLATE pg_catalog."default",
    level text COLLATE pg_catalog."default",
    source_framework text COLLATE pg_catalog."default" NOT NULL,
    source_id text COLLATE pg_catalog."default",
    embedding_model text COLLATE pg_catalog."default" NOT NULL,
    embedding vector(384) NOT NULL,
    CONSTRAINT skill_taxonomy_pkey PRIMARY KEY (skill_id)
);

CREATE TABLE IF NOT EXISTS rerouteher.source_manifest
(
    relative_path text COLLATE pg_catalog."default" NOT NULL,
    provider text COLLATE pg_catalog."default" NOT NULL,
    version_or_date text COLLATE pg_catalog."default",
    source_url text COLLATE pg_catalog."default",
    licence_or_reuse_note text COLLATE pg_catalog."default",
    bytes bigint NOT NULL,
    sha256 text COLLATE pg_catalog."default" NOT NULL,
    acquired_on date,
    scope_restriction text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT source_manifest_pkey PRIMARY KEY (relative_path)
);

CREATE TABLE IF NOT EXISTS rerouteher.task_compliance
(
    task text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    completed text COLLATE pg_catalog."default" NOT NULL,
    remaining_gate text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT task_compliance_pkey PRIMARY KEY (task)
);

CREATE TABLE IF NOT EXISTS rerouteher.task_rating_reviews
(
    masco_task_id text COLLATE pg_catalog."default" NOT NULL,
    role_id text COLLATE pg_catalog."default" NOT NULL,
    task text COLLATE pg_catalog."default" NOT NULL,
    remote_task_pre_rating text COLLATE pg_catalog."default" NOT NULL,
    remote_rule_evidence text COLLATE pg_catalog."default",
    ai_task_pre_rating text COLLATE pg_catalog."default" NOT NULL,
    ai_rule_evidence text COLLATE pg_catalog."default",
    rating_method text COLLATE pg_catalog."default" NOT NULL,
    rater_1 text COLLATE pg_catalog."default",
    rater_1_rating text COLLATE pg_catalog."default",
    rater_2 text COLLATE pg_catalog."default",
    rater_2_rating text COLLATE pg_catalog."default",
    reconciled_rating text COLLATE pg_catalog."default",
    review_status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT task_rating_reviews_pkey PRIMARY KEY (masco_task_id)
);

ALTER TABLE IF EXISTS rerouteher.caregiving_map
    ADD CONSTRAINT caregiving_map_onet_skill_id_fkey FOREIGN KEY (onet_skill_id)
    REFERENCES rerouteher.skill_taxonomy (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.d9_target_role_mapping
    ADD CONSTRAINT d9_target_role_mapping_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS d9_target_role_mapping_pkey
    ON rerouteher.d9_target_role_mapping(role_id);


ALTER TABLE IF EXISTS rerouteher.d9_training_examples
    ADD CONSTRAINT d9_training_examples_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.digital_skill_rating_lineage
    ADD CONSTRAINT digital_skill_rating_lineage_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.digital_skill_rating_lineage
    ADD CONSTRAINT digital_skill_rating_lineage_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES rerouteher.skill_taxonomy (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.employer_evidence
    ADD CONSTRAINT employer_evidence_employer_id_fkey FOREIGN KEY (employer_id)
    REFERENCES rerouteher.employers (employer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.employer_report_evidence
    ADD CONSTRAINT employer_report_evidence_employer_id_fkey FOREIGN KEY (employer_id)
    REFERENCES rerouteher.employers (employer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS employer_report_evidence_pkey
    ON rerouteher.employer_report_evidence(employer_id);


ALTER TABLE IF EXISTS rerouteher.employer_report_search
    ADD CONSTRAINT employer_report_search_employer_id_fkey FOREIGN KEY (employer_id)
    REFERENCES rerouteher.employers (employer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS employer_report_search_pkey
    ON rerouteher.employer_report_search(employer_id);


ALTER TABLE IF EXISTS rerouteher.employer_review_queue
    ADD CONSTRAINT employer_review_queue_employer_id_fkey FOREIGN KEY (employer_id)
    REFERENCES rerouteher.employers (employer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS employer_review_queue_pkey
    ON rerouteher.employer_review_queue(employer_id);


ALTER TABLE IF EXISTS rerouteher.employers
    ADD CONSTRAINT employers_sector_id_fkey FOREIGN KEY (sector_id)
    REFERENCES rerouteher.bursa_sectors (sector_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.jobhop_esco_features
    ADD CONSTRAINT jobhop_esco_features_esco_code_fkey FOREIGN KEY (esco_code)
    REFERENCES rerouteher.occupation_profiles (esco_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS jobhop_esco_features_esco_idx
    ON rerouteher.jobhop_esco_features(esco_code);


ALTER TABLE IF EXISTS rerouteher.learning_resource
    ADD CONSTRAINT learning_resource_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES rerouteher.provider (provider_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS learning_resource_provider_id_idx
    ON rerouteher.learning_resource(provider_id);


ALTER TABLE IF EXISTS rerouteher.learning_resource_skill
    ADD CONSTRAINT learning_resource_skill_resource_id_fkey FOREIGN KEY (resource_id)
    REFERENCES rerouteher.learning_resource (resource_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS rerouteher.learning_resource_skill
    ADD CONSTRAINT learning_resource_skill_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES rerouteher.skill_taxonomy (skill_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS learning_resource_skill_skill_id_idx
    ON rerouteher.learning_resource_skill(skill_id);


ALTER TABLE IF EXISTS rerouteher.minilm_embeddings
    ADD CONSTRAINT minilm_embeddings_esco_code_fkey FOREIGN KEY (esco_code)
    REFERENCES rerouteher.occupation_profiles (esco_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS minilm_embeddings_pkey
    ON rerouteher.minilm_embeddings(esco_code);


ALTER TABLE IF EXISTS rerouteher.occupation_skill_weights
    ADD CONSTRAINT occupation_skill_weights_esco_code_fkey FOREIGN KEY (esco_code)
    REFERENCES rerouteher.occupation_profiles (esco_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.official_role_crosswalk
    ADD CONSTRAINT official_role_crosswalk_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS official_role_crosswalk_pkey
    ON rerouteher.official_role_crosswalk(role_id);


ALTER TABLE IF EXISTS rerouteher.onet_task_context
    ADD CONSTRAINT onet_task_context_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_rating_lineage
    ADD CONSTRAINT role_rating_lineage_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS role_rating_lineage_pkey
    ON rerouteher.role_rating_lineage(role_id);


ALTER TABLE IF EXISTS rerouteher.role_sector_map
    ADD CONSTRAINT role_sector_map_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_sector_map
    ADD CONSTRAINT role_sector_map_sector_id_fkey FOREIGN KEY (sector_id)
    REFERENCES rerouteher.bursa_sectors (sector_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_sector_review_queue
    ADD CONSTRAINT role_sector_review_queue_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_sector_review_queue
    ADD CONSTRAINT role_sector_review_queue_sector_id_fkey FOREIGN KEY (sector_id)
    REFERENCES rerouteher.bursa_sectors (sector_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_skill_lineage
    ADD CONSTRAINT role_skill_lineage_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_skill_lineage
    ADD CONSTRAINT role_skill_lineage_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES rerouteher.skill_taxonomy (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_skills
    ADD CONSTRAINT role_skills_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.role_skills
    ADD CONSTRAINT role_skills_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES rerouteher.skill_taxonomy (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS role_skills_skill_idx
    ON rerouteher.role_skills(skill_id);


ALTER TABLE IF EXISTS rerouteher.role_tasks
    ADD CONSTRAINT role_tasks_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.saved_journey
    ADD CONSTRAINT saved_journey_auth_subject_fkey FOREIGN KEY (auth_subject)
    REFERENCES rerouteher.app_user (auth_subject) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS saved_journey_auth_subject_idx
    ON rerouteher.saved_journey(auth_subject);


ALTER TABLE IF EXISTS rerouteher.saved_journey
    ADD CONSTRAINT saved_journey_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS saved_journey_role_id_idx
    ON rerouteher.saved_journey(role_id);


ALTER TABLE IF EXISTS rerouteher.shortlist_item
    ADD CONSTRAINT shortlist_item_employer_id_fkey FOREIGN KEY (employer_id)
    REFERENCES rerouteher.employers (employer_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS shortlist_item_employer_id_idx
    ON rerouteher.shortlist_item(employer_id);


ALTER TABLE IF EXISTS rerouteher.shortlist_item
    ADD CONSTRAINT shortlist_item_journey_id_fkey FOREIGN KEY (journey_id)
    REFERENCES rerouteher.saved_journey (journey_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS rerouteher.skill_aliases
    ADD CONSTRAINT skill_aliases_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES rerouteher.skill_taxonomy (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rerouteher.task_rating_reviews
    ADD CONSTRAINT task_rating_reviews_masco_task_id_fkey FOREIGN KEY (masco_task_id)
    REFERENCES rerouteher.role_tasks (masco_task_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS task_rating_reviews_pkey
    ON rerouteher.task_rating_reviews(masco_task_id);


ALTER TABLE IF EXISTS rerouteher.task_rating_reviews
    ADD CONSTRAINT task_rating_reviews_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES rerouteher.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;